#!/usr/bin/env Rscript

# last edited 31 Oct 2022, Albert Vill, acv46@cornell.edu

# Functionality
## merges the outputs of checkm and gtdbtk from clean_assemble_bin.sh

# Output
## a single summary file, ${NAME}_binSummary.txt

message(R.Version()$version.string)
message(paste("Checking for required libraries"))

list.of.packages <- c("optparse","dplyr","readr","tidyr","stringr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) {
  message(paste0("Installing packages: ", paste(new.packages, collapse = ", ")))
  install.packages(new.packages)
}
suppressMessages(library("optparse"))
suppressMessages(library("readr"))
suppressMessages(library("dplyr"))
suppressMessages(library("tidyr"))

option_list <- list(
  optparse::make_option(c("-q", "--quality_report"),
                        action = "store",
                        type = "character",
                        default = NULL,
                        help = "REQUIRED: completeness and contamination report generated by checkm2 predict",
                        metavar = "character"),
  optparse::make_option(c("-a", "--abundance_report"),
                        action = "store",
                        type = "character",
                        default = NULL,
                        help = "REQUIRED: abundance report generated by checkm profile",
                        metavar = "character"),
  optparse::make_option(c("-g", "--gtdbtk"),
                        action = "store",
                        type = "character",
                        default = NULL,
                        help = "REQUIRED: GTDB-Tk taxa summary",
                        metavar = "character"),
  optparse::make_option(c("-o", "--out_dir"),
                        action = "store",
                        type = "character",
                        default = getwd(),
                        help = "Output directory without trailing \"/\" (default: getwd())",
                        metavar = "character"),
  optparse::make_option(c("-n", "--name"),
                        action = "store",
                        type = "character",
                        default = NULL,
                        help = "REQUIRED: name to append to output file (${NAME}_BINSTATS.txt)",
                        metavar = "character"))
opt_parser <- optparse::OptionParser(option_list = option_list)
opt <- optparse::parse_args(opt_parser)

qual <- readr::read_tsv(file = paste(opt$quality_report), col_names = TRUE) |>
  dplyr::rename(bin = 1,
         completeness_general = 2,
         contamination = 3,
         completeness_specific = 4,
         model = 5,
         translation_table = 6,
         notes = 7) |>
  dplyr::mutate(completeness = ifelse(model == "Neural Network (Specific Model)",
                               yes = completeness_specific,
                               no = completeness_general)) |>
  dplyr::select(-c(completeness_general, completeness_specific, notes, translation_table))

abun <- readr::read_tsv(file = paste(opt$abundance_report), col_names = TRUE) |>
  dplyr::rename(bin = 1,
         Mbp = 2,
         mapped_reads = 3,
         percent_mapped_reads = 4,
         percent_binned_populations = 5,
         percent_community = 6)

gtdb <- readr::read_tsv(file = paste(opt$gtdbtk), col_names = T, na = "N/A") |>
  dplyr::rename(bin = 1,
         classification = 2,
         closest_reference = 8,
         gtdbtk_warnings = 20) |>
  dplyr::select(bin, classification, closest_reference, gtdbtk_warnings) |>
  dplyr::mutate(classification = stringr::str_remove_all(string = classification, pattern = "\\D__")) |>
  tidyr::separate(classification, into = c("domain", "phylum", "class",
                                    "order", "family", "genus", "species"),
           sep = ";",
           fill = "right") |>
  dplyr::mutate_all(~na_if(.,""))

full <- qual |>
  dplyr::full_join(abun, by = "bin") |>
  dplyr::full_join(gtdb, by = "bin")

setwd(opt$out_dir)
write.table(x = full, 
            row.names = FALSE, 
            sep="\t", 
            quote = FALSE,
            file = paste(opt$out_dir, paste0(opt$name, "_binSummary.txt"), sep = "/"))
